server:
  port: 8200


# 设置nacos的地址（配置中心）
nacos:
  discovery:
    server-addr: hadoop101:8848

# Dubbo 广播方式配置，如果调用不稳定可以修改为直连模式：https://codechina.csdn.net/KnowledgePlanet/Lottery/-/issues/1
dubbo:
  application:
    name: lottery-admin-api
    version: 1.0.0
  registry:
    address: nacos://hadoop101:8848
  protocol:
    name: dubbo
    port: -1


spring:
  application:
    name: lottery-admin-api





