version: '3'
services:
  mysql:
    image: mysql:latest
    restart: always
    network_mode: host
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M;
    ports:
      - 3306:3306
    volumes:
      - /data/mysql:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
      - /etc/my.cnf:/etc/my.cnf