version: "3"

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "rootroot"
      TZ: Asia/Shanghai

  redis:
    image: redis:6.0.8
    container_name: redis
    restart: always
    privileged: true
    deploy:
      resources:
        limits:
          memory: 200M
    ports:
      - "6379:6379"
    environment:
      IP: 0.0.0.0
      TZ: Asia/Shanghai
    volumes:
      - /root/docker/config/redis:/data
      - /etc/localtime:/etc/localtime:ro

  rabbitmq:
    image: rabbitmq:3.12.6-management
    container_name: rabbitmq_3_12
    restart: always
    # 节点名 rabbit@rabbitserver，不然会去容器ID
    hostname: rabbit_server
    environment:
      # 默认虚拟机名
      RABBITMQ_DEFAULT_VHOST: admin_vhost
      # 用户名
      RABBITMQ_DEFAULT_USER: root
      # 密码
      RABBITMQ_DEFAULT_PASS: 123456
      # 指定自定义插件目录
      RABBITMQ_PLUGINS_DIR: '/plugins:/myplugins'
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - /root/docker/rabbitmq/data:/var/lib/rabbitmq
      - /root/docker/rabbitmq/plugin:/myplugins


  kafka:
    image: bitnami/kafka:3.3
    container_name: kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: hadoop101:2181
      TZ: Asia/Shanghai
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://hadoop101:9092
      KAFKA_ADVERTISED_HOST_NAME: hadoop101
      KAFKA_LOG_RETENTION_HOURS: 24
    depends_on:
      - zookeeper

  zookeeper:
    image: zookeeper
    container_name: zookeeper
    restart: always
    deploy:
      resources:
        limits:
          memory: 500M
    ports:
      - "2181:2181"
    environment:
        TZ: Asia/Shanghai


  nacos:
    image: nacos/nacos-server:v2.1.0
    privileged: true
    container_name: nacos
    network_mode: host
    deploy:
      resources:
        limits:
          memory: 1G
    environment:
      # 支持主机名可以使用hostname,否则使用ip，默认ip
      - PREFER_HOST_MODE=ip
      # 单机模式
      - MODE=standalone
      # 数据源平台 支持mysql或不保存empty
      - SPRING_DATASOURCE_PLATFORM=mysql
      # mysql配置，!!!attention必须是mysql所在主机IP
      - MYSQL_SERVICE_HOST=hadoop101
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=rootroot
      - MYSQL_SERVICE_DB_NAME=nacos
    volumes:
      - /root/docker/logs/nacos:/home/nacos/logs
      - /root/docker/config/nacos:/home/nacos/conf
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    depends_on:
      - mysql
    restart: always

  xxl-job-admin:
    restart: always
    # docker 镜像
    image: xuxueli/xxl-job-admin:2.2.0
    # 容器名称
    container_name: xxl-job-admin
    platform: "linux/arm64"
    deploy:
      resources:
        limits:
          memory: 1G
    volumes:
      # 日志目录映射到主机目录
      - /root/docker/log/xxl-job:/data/applogs
    ports:
      # 端口映射
      - "8800:8800"
    environment:
      # 设置启动参数
      PARAMS: '
        --server.port=8800
        --server.servlet.context-path=/xxl-job-admin
        --spring.datasource.url=jdbc:mysql://hadoop101:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
        --spring.datasource.username=root
        --spring.datasource.password=rootroot
        --xxl.job.accessToken=onelovehzs888'  #代码里面需要指定的token


