server:
  port: 8000

spring:
  application:
    name: activity-base
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: rootroot
    url: jdbc:mysql://hadoop101:3306/marketing_activity_base
  redis:
    database: 0
    host: hadoop101     # Redis服务器地址，修改为你的地址
    port: 6379          # Redis服务器连接端口
    password:           # Redis服务器连接密码（默认为空）
    timeout: 3000       # Redis服务器链接超时配置

# nacos 配置中心
nacos:
  discovery:
    server-addr: hadoop101:8848

# Dubbo 广播方式配置，如果调用不稳定可以修改为直连模式：https://codechina.csdn.net/KnowledgePlanet/Lottery/-/issues/1
dubbo:
  application:
    name: activity-base
    version: 1.0.0
  #    parameters:
  #      unicast: false
  registry:
    address: nacos://hadoop101:8848
  protocol:
    name: dubbo
    port: -1
    queues: 200
    threads: 300
  scan:
    base-packages: marketing.activity.base.application.rpc


rule:
  engine:
    groovy:
      redis-loader:
        enable: true
      # 脚本检查更新周期（单位：秒），（默认300L）
      pollingCycle: 10000
      # 开启功能
      enable: true
      # 缓存过期时间(默认600L分钟)
      cacheExpireAfterWrite: 20
      #缓存初始容量(默认100)
      cacheInitialCapacity: 10
      # 缓存最大容量(默认500)
      cacheMaximumSize: 50