server:
  port: 8888


# 设置nacos的地址（配置中心）
nacos:
  discovery:
    server-addr: hadoop101:8848

# Dubbo 广播方式配置，如果调用不稳定可以修改为直连模式：https://codechina.csdn.net/KnowledgePlanet/Lottery/-/issues/1
dubbo:
  application:
    name: marketing-activity-consumer
    version: 1.0.0
  registry:
    address: nacos://hadoop101:8848
  protocol:
    name: dubbo
    port: -1

# Mybatis
mybatis-plus:
  global-config:
    banner: false
    db-config:
      id-type: ID_WORKER
      logic-delete-value: 1
      logic-not-delete-value: 0
      insert-strategy: NOT_NULL
      update-strategy: NOT_NULL
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: rootroot
    url: jdbc:mysql://hadoop101:3306/marketing_activity